### ISSUE TITLE
Arrange the blogs post according the time of upload  or arrange latest blog at first

### ISSUE THREAD

**Issue by tajmalnas** [AKD-01/blogweet#101]
as of now the post are showing randomly their is no arrangement or order like you can see latest uploaded post goes on third or fourth position but i can fix this issue this will make your home post feed updated "Latest post will be displays first "
![Screenshot (31)](https://github.com/AKD-01/blogweet/assets/111240245/daf855a3-9122-46e8-852d-79e349cf2428)

**Comment by tajmalnas** [comment]
you can see that post which is uploaded at 24 is below post which is uploaded at 22

**Comment by tajmalnas** [comment]
please assign me this issue so that i can work on it

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.

**Comment by tajmalnas** [comment]
@AKD-01 I want to make pr but there is one error from firebase which only you can fix or someone who has acces to firebase their we need to enable index in query as it takes to query to solve this issue but no problem
