### ISSUE TITLE
UI of blogs in Blogweet

### ISSUE THREAD

**Issue by shruti8302** [AKD-01/blogweet#106]
Hey @AKD-01, as a part of GSSOC'23, I would like to change the UI of blogs by improving the fonts as well as text content styling properties. Kindly assign me the issue.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by AKD-01** [comment]
Hi, @shruti8302  you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by shruti8302** [comment]
@AKD-01 Thanks I will work on it. But could you please label this issue under GSSOC'23?
