### ISSUE TITLE
Add Hover effect on each Blog Card

### ISSUE THREAD

**Issue by abhinav-m22** [AKD-01/blogweet#110]
In the card component of each Blog, adding some hover effects and animations can improve the UX and a seamless experience to the user.
I want to work on these feature improvement.
Please assign me the task under GSSoC'23.

**Comment by AKD-01** [comment]
Hey @abhinav-m22, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by abhinav-m22** [comment]
Hey @AKD-01 ..
I've created the PR - #193 
Please have a look
