### ISSUE TITLE
inconsistent asynchronous functions

### ISSUE THREAD

**Issue by sachdevavaibhav** [AKD-01/blogweet#111]
I noticed the codebase is not consistent in terms of writing asynchronous functions. Somewhere there is .then() used and somewhere async and await is used.

For example in app.js the ```signOut``` function uses .then() and in createPost.js ```createPost``` function uses async await syntax.

You can assign me this issue and I can work on it.

@AKD-01

**Comment by AKD-01** [comment]
Hey @sachdevavaibhav, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!
