### ISSUE TITLE
Upvote and Downvote to the blogs

### ISSUE THREAD

**Issue by Satyam0204** [AKD-01/blogweet#112]
We can make a rating system to the blogs whoever reads it can upvote it if he/she likes the blog and can downvote if he/she doesn't likes.

Please assign this to me. I would love to work on this as a GSSOC 23' Contributor.

**Comment by khushi1711** [comment]
i want to work on this issue

**Comment by AKD-01** [comment]
Hi @Satyam0204, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
