### ISSUE TITLE
Change the CARD UI and Sidebar UI

### ISSUE THREAD

**Issue by PRIZZA21** [AKD-01/blogweet#115]
The blogs card is pretty basic. I want to use glassmorphism and 3D effects to improve the UI of card by adding animations and gradients 
I would like to work on this issue under GSSOC'23. Please assign me this issue

**Comment by Manvi1902** [comment]
i would like to contribute in this.

**Comment by AKD-01** [comment]
Hi, @PRIZZA21  you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
