### ISSUE TITLE
Modify create post form UI.

### ISSUE THREAD

**Issue by Aarav238** [AKD-01/blogweet#123]
I will modify the form UI using css and css framework.
Here is the current form:-
![image](https://github.com/AKD-01/blogweet/assets/95538627/00074eb9-fe4b-46af-af82-8e970f237015)

**Comment by Cadit21** [comment]
I would like to work on this issue.
I would like to  improve the ui of this page .

**Comment by AKD-01** [comment]
Hi, @Aarav238 , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
