### ISSUE TITLE
Template for people to have a proper format for bug fix, pull requests, new feature addition etc. 

### ISSUE THREAD

**Issue by tuhinaww** [AKD-01/blogweet#132]
| Field | Value                           |
|-------|---------------------------------|
| About | Template for people to have a proper format for bug fix, pull requests, new feature addition etc. |
| Title |       Feature request             |
| **Is your feature request related to a problem? Please describe.** | New Contributors are not able to follow a proper format to create issue for bug fixes, pull request,  new feature additions etc. |
| **Describe the solution you'd like**                               | I can provide ".github" folder with all the necessary templates required |
| **Additional context**                                             | I am from GSSOC'23 you can assign this issue to me |

**Comment by AKD-01** [comment]
Hi, @tuhinaww you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by tuhinaww** [comment]
Thanks! I'll start working on this!
