### ISSUE TITLE
Want to change the desgin and size of card and making it more desginable.

### ISSUE THREAD

**Issue by Manvi1902** [AKD-01/blogweet#133]
![image](https://github.com/AKD-01/blogweet/assets/109518835/d11200a1-bc90-4bae-9d96-ce1953d9cd77)

please assign me this

**Comment by Cadit21** [comment]
I  would like to work on this issue. I would like to change the size of cards and want to do UI enhancement of this  page.
pls assign this to me.

**Comment by AKD-01** [comment]
Hi, @Manvi1902, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by Manvi1902** [comment]
mam could you please tell the deadline of completing the task.

**Comment by AKD-01** [comment]
Its 1 week.
And closing this because of no response or pr from your side.
