### ISSUE TITLE
add content ,write section, testimonial

### ISSUE THREAD

**Issue by Rohit-osc** [AKD-01/blogweet#134]
As in the website some section are vacant so I would like to add some content.
I think there should be write section where user can  share their knowledge and experience.
Also if there is a feature of testimonial which shows how this website helps user ,it will give more insight about website.

I request you to assign this task to me under gssoc'23.

**Comment by AKD-01** [comment]
Hi, @Rohit-osc , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by Rohit-osc** [comment]
Thanks! I will start working on this.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
