### ISSUE TITLE
Add Scroll to Top 

### ISSUE THREAD

**Issue by Deepanshu0703** [AKD-01/blogweet#136]
As the Home page is too long so there must be a scroll to top button so i added the button 
![Screenshot (12)](https://github.com/AKD-01/blogweet/assets/114489502/2ac0933c-12f1-4192-a3d2-b64c69c3452c)

All checks have been passed and thus I made the PR

**Comment by AKD-01** [comment]
this issue was already assigned to someone, so please wait for the issue being assigned to you before raising a pr
