### ISSUE TITLE
Grammitical errors in About section

### ISSUE THREAD

**Issue by HimanshuNarware** [AKD-01/blogweet#140]
The website About section has some grammatical errors
please  assign me this issue
![Screenshot 2023-05-22 194309](https://github.com/AKD-01/blogweet/assets/83147410/ccc3bcdf-a98e-41ea-a26e-c533bca462a2)

**Comment by AKD-01** [comment]
Issue which you raised is not grammatically correct. :)

**Comment by HimanshuNarware** [comment]
> Issue which you raised is not grammatically correct. :)

sorry its spelling mistake
