### ISSUE TITLE
Log in Page need some improvement

### ISSUE THREAD

**Issue by HimanshuNarware** [AKD-01/blogweet#141]
Want to improve the log in page
![Screenshot 2023-05-22 194618](https://github.com/AKD-01/blogweet/assets/83147410/ab8d4b59-8d92-44b3-91a9-785f5a722f67)

**Comment by AKD-01** [comment]
Hi, @HimanshuNarware , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!
