### ISSUE TITLE
Add table of content

### ISSUE THREAD

**Issue by mhr1812** [AKD-01/blogweet#144]
I can add a table of content as mentioned below to readme.md for easy navigation, can you assign me this issue to me under GSSOC'23?
![tabofcontent](https://github.com/AKD-01/blogweet/assets/89465612/592397ae-4e9c-418a-a794-9f276bb49be4)

**Comment by AKD-01** [comment]
Hi, @mhr1812  you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!
