### ISSUE TITLE
Improving UI of the Website.

### ISSUE THREAD

**Issue by saiwali** [AKD-01/blogweet#146]
The UI of different containers used does not seem to match the left-side list section. I can improve the UI and make the Website even better. Can you assign this issue to me under GSSOC'23?

**Comment by AKD-01** [comment]
Hi, @saiwali , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
