### ISSUE TITLE
Add progress scroll bar at the top 

### ISSUE THREAD

**Issue by heyhimansh** [AKD-01/blogweet#149]
Hey @AKD-01 , I want to add a progress scroll bar that helps in making your website more interactive . 

example : one of my project [link](https://bank-resposnive-web-home.vercel.app/)

![BlogWeet and 123 more pages - Personal 2 - Microsoft​ Edge 22-05-2023 23_40_02 (2)](https://github.com/AKD-01/blogweet/assets/72097380/32b5aad9-dc68-44b3-9dae-bbfb7fa6ee74)

I hope these suggestions help you in your web design improvements. Assign this issue to me under gssoc2023

**Comment by Himanshi1207** [comment]
I can work on the issue please assign it to me under GSSoC'23.

**Comment by AKD-01** [comment]
@heyhimansh this issue has now been resolved.
![image](https://github.com/AKD-01/blogweet/assets/83454075/33a8727f-6b5e-4bf9-b92e-bb7ded75a29c)
But you may shift it little rightwards and can add more styles to it.

**Comment by Himanshi1207** [comment]
working on it.

**Comment by heyhimansh** [comment]
I have been already assigned this issue and worked on it @Himanshi1207   U can find another issue and contribute their.
Before working on any issue please read all the guidelines.
