### ISSUE TITLE
Add Preloader in React Application

### ISSUE THREAD

**Issue by heyhimansh** [AKD-01/blogweet#150]
hey @AKD-01 , i want to add preloader to your react application that provides modern UI . This will also helps in loading the other components of application faster.

Demo :[Link](https://codesandbox.io/s/dim505test3-snrmu)
I hope these suggestions help you in your web design improvements. Assign this issue to me under gssoc2023

**Comment by AKD-01** [comment]
@Prap1 has already worked on it but Please before taking any issue let me assign it to you first then only work on that in future. And @heyhimansh I have assigned you another issue you may work on that.
