### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by km1610** [AKD-01/blogweet#153]
There can be several improvements with the UI to make it more engaging to the users.
Cards and the color combinations can be changed and made more attractive. Currently the UI looks very dull and non-interactive.
Kindly assign this issue to me. I work as a web designer and can work on enhancing the UI nicely

**Comment by AKD-01** [comment]
Hi, @km1610 , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
