### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by crocmons** [AKD-01/blogweet#154]
we have to make it responsive

![Screenshot (324)](https://github.com/AKD-01/blogweet/assets/106610322/b7f23b72-2cbb-4f0a-9a8c-5d2996ae89e1)

**Comment by crocmons** [comment]
Can you assign this issue to me under GSSOC'23?

**Comment by AKD-01** [comment]
Already assigned issue, please check all the issues before creating any new issue.
