### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by crocmons** [AKD-01/blogweet#156]
we have to add the hamburger menu on this so that user can see the homepage
Can you assign this issue to me under GSSOC'23?

![Screenshot (325)](https://github.com/AKD-01/blogweet/assets/106610322/dbae2e90-5f0a-4e6e-818a-f906edef216f)

**Comment by AKD-01** [comment]
We don't need hamburger menu.

**Comment by crocmons** [comment]
ok, as your wish.. but if you not add this how the user can read the pages if the content is not visible for that navbar?
![Screenshot (336)](https://github.com/AKD-01/blogweet/assets/106610322/5f48a5e2-2adb-4517-beb1-a51dd02e0d55)
