### ISSUE TITLE
Hover effect on the submit button

### ISSUE THREAD

**Issue by Kaivanshah1** [AKD-01/blogweet#157]
There should be a hover effect on the submit button.
Assign me this issue.

**Comment by ShubhiG30** [comment]
i would like to work on this...please assign this to me.

**Comment by AKD-01** [comment]
Hi, @Kaivanshah1 , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
