### ISSUE TITLE
Make card image responsive and fit to the card

### ISSUE THREAD

**Issue by heyhimansh** [AKD-01/blogweet#158]
Hey @AKD-01 , I want to add some good UI to the card section that makes it responsive and  interactive .

![BlogWeet and 127 more pages - Personal 2 - Microsoft​ Edge 23-05-2023 09_32_45 (2)](https://github.com/AKD-01/blogweet/assets/72097380/260dd19d-96c3-4697-a5cb-1b91d47a7fcc)

Like here the images is not fit with border or even white border looks odd. This can be resolve by removing border and add some border radius. Also increasing the padding of whole card makes cards component interactive.

**Comment by Shahil093** [comment]
HTML:-

<div class="card">
  <img src="image.jpg" alt="Card Image">
</div>


CSS:-

.card {
  width: 100%;
  max-width: 400px; 
}
.card img {
  width: 100%; 
  height: auto; 
  display: block; 
}

**Comment by AKD-01** [comment]
Hi, @heyhimansh , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
I'm not able to see your changes effectively as right now there in no written content for any blog, would you like to work on that first? AS then only i will be able to your changes effectively. Right now, I can't.
![image](https://github.com/AKD-01/blogweet/assets/83454075/daf48d90-6124-4178-bba1-00a366b0be83)
There is an issue created by me in the issue section, tag me there if you would like to work.

**Comment by khadar1020** [comment]
can i work on this issue
