### ISSUE TITLE
[Feat] implement share functionality

### ISSUE THREAD

**Issue by subrat611** [AKD-01/blogweet#163]
**Could you please assign this issue to me?**

![image](https://github.com/AKD-01/blogweet/assets/77252075/70602ff7-29a1-4441-8296-7966323a459e)

**Comment by AKD-01** [comment]
Hi, @subrat611 , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.

**Comment by subrat611** [comment]
Due my end sem examination I am not able to work on this issue.

If the issue has been fixed let me know.
