### ISSUE TITLE
Non-responsive CREATE POST page

### ISSUE THREAD

**Issue by marshadkhn** [AKD-01/blogweet#166]
Hey @AKD-01 and @srivastavaritik, I gone through the project and all the issues and got one issue in `CREATE POST` page. The page is not responsive at all

Actual state - 
![Screenshot 2023-05-23 160055](https://github.com/AKD-01/blogweet/assets/80325579/75ce38ac-f09a-4cff-8672-6809e924af60)

**Assign me this issue I will send PR**
My branch name - marshadkhn

**Comment by AKD-01** [comment]
Hi, @marshadkhn  you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Hey, @marshadkhn  thank you for your contribution and patience, I will be reviewing your pr soon. If you liked the project, don't forget to give it a star.
