### ISSUE TITLE
[GSSoc'23] Making the app responsive and make it more attractive

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [AKD-01/blogweet#167]
Hey @AKD-01  
I'm a GSSoC'23 contributor and I would like to add responsiveness to your WebApp. The various webpages are'nt responsive to screen size this would provide a bad user experience to the users visiting it through devices other than a pc.

Kindly assign this issue to me so I could provide a fix for it.

**Comment by AKD-01** [comment]
Hi, @rishabhchaudhary0210 , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best! Please mention issue no while raising the pr.

**Comment by rishabhchaudhary0210** [comment]
Hey, @AKD-01 I have fixed the issue in the SideBar and now it doesn't break for any device.
Also the checks have passed kindly review and merge it.
