### ISSUE TITLE
Adding Tech Stacks Used in ReadMe Section

### ISSUE THREAD

**Issue by abhiruchisarswat** [AKD-01/blogweet#171]
I want to add Technology Stack used in the ReadMe. This would be quite helpful for contributors who are looking forward to contributing to the blog tweet.

This would enhance the readMe section. 
Plz, assign me this task.

**Comment by abhi03ruchi** [comment]
ok

**Comment by abhi03ruchi** [comment]
Hi, @AKD-01, I have resolved Issue #171 and raised a pr. Please review and merge it.
