### ISSUE TITLE
The content is missing...

### ISSUE THREAD

**Issue by ombhojane** [AKD-01/blogweet#172]
I'd found that the blogs are not their in website. I'm a technical writer and knows the importance of content writing for website engagement. I can write meaningful blogs for website and update them in section.
Also, you can suggest some topics, I'm planning to write on web3, metaverse, ai and human relationships and much more...
Can you please assign this issue to me..
GSSOC 2023 :)

**Comment by AKD-01** [comment]
Hi, @ombhojane  you may work on this and please refer to the Contribution guidelines on the readme once.
All the best! Please mention issue no while raising the pr.

**Comment by ombhojane** [comment]
thankyou!! for assigning this issue, I'm working on this with my best

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
