### ISSUE TITLE
Update Sign In buttons

### ISSUE THREAD

**Issue by Ayushhgupta39** [AKD-01/blogweet#186]
I want to update the Sign in with GitHub and sign in with Google buttons giving them a much more professional look. 
<img width="373" alt="image" src="https://github.com/AKD-01/blogweet/assets/96309609/253d607f-dcee-4fa7-b8d0-31f735a13076">
Please assign me this issue.

**Comment by AKD-01** [comment]
Please read readme.md and mention the issue no while raising the pr.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
