### ISSUE TITLE
Add New Favicon

### ISSUE THREAD

**Issue by Ayushhgupta39** [AKD-01/blogweet#188]
I want to add a new favicon to the website replacing the old One which is as same as Twitter. The new logo will be completely the website's own and customized.

**Comment by AdityaGoel0320** [comment]
I have to work on this issue kindly assign me it under gssoc 2023 tag

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
