### ISSUE TITLE
Home Card Text Hover Effect, Login Button, and Card Color Combination Improvements

### ISSUE THREAD

**Issue by manaver** [AKD-01/blogweet#195]
## Description:
The home page of the website requires some improvements to enhance the user experience and visual appeal. The following issues have been identified:

1. Home Card Text Hover Effect and Shadow:
The text hover effect on the home cards is not visually engaging or intuitive. It needs improvement to provide a clear indication of interactivity. Additionally, the shadow applied to the cards should be adjusted to achieve a better visual effect.

2. Login Button:
The current design of the login button is perceived as irritating or distracting. It needs to be improved to provide a more pleasant and user-friendly experience. Consider using a different color, style, or placement to make it more visually appealing and less intrusive.

3. Card Color Combination:
The color combination used for the cards on the home page could be enhanced to create a better visual harmony and improve readability. Consider selecting colors that complement each other and ensure sufficient contrast between the background and text.

### Proposed Solution:
To address these issues and improve the home page:

1. Enhance the text hover effect on the home cards to make it more visually engaging and intuitive. Adjust the shadow applied to the cards to achieve a better visual effect.

2. Improve the design of the login button by using a different color, style, or placement to make it more visually appealing and less distracting.

3. Revise the color combination of the cards to create a better visual harmony. Select colors that complement each other and ensure sufficient contrast between the background and text.

**Comment by manaver** [comment]
Please assign this issue to me

**Comment by AKD-01** [comment]
Please read readme.md and mention the issue no while raising the pr.

**Comment by manaver** [comment]
> Please read readme.md and mention the issue no while raising the pr.

Ok

**Comment by manaver** [comment]
@AKD-01 Please add gssoc tag 😄

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me
