### ISSUE TITLE
add code of conduct

### ISSUE THREAD

**Issue by S-ishita** [AKD-01/blogweet#196]
Hi there!
I recommend adding a CODE_OF_CONDUCT.md file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under GSSoC'23.

Thank you!

**Comment by AKD-01** [comment]
Hey @S-ishita, instead of making separate issues for changing a single file, please raise a single issue mentioning all the changes from next time.

**Comment by S-ishita** [comment]
I had no issue related to code of conduct earlier.. previous once were related to readme , though me will keep in mind the same

**Comment by AKD-01** [comment]
But code of conduct will also be the part of the readme right, so if there are anymore changes you want to do in the readme section do it all and then raise the pr.
