### ISSUE TITLE
Add footer in all the pages

### ISSUE THREAD

**Issue by Gunjanrathore8178** [AKD-01/blogweet#197]
Footer is missing. please assign this project to me

**Comment by AKD-01** [comment]
Please read readme.md and mention the issue no while raising the pr.

**Comment by Gunjanrathore8178** [comment]
Please put the tag GSSOC. It's a humble request

**Comment by AKD-01** [comment]
When you will raise the pr and it will get merged will put the tags then, don't worry.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
