### ISSUE TITLE
side bar is not responsive

### ISSUE THREAD

**Issue by Prashant-2505** [AKD-01/blogweet#20]
the side bar of website is not responsive its not look good for small devices like pads and mobile phone 
 
 i can fix it 

can you assign this issue to me  (Gssoc '23 contributor)

![Screenshot (35)](https://github.com/AKD-01/blogweet/assets/102030344/3dc7dbbd-afa6-441e-b96b-616b41984eca)

**Comment by Prashant-2505** [comment]
it cover the half portion of the page

**Comment by AKD-01** [comment]
It was meant to be like that only, but if you want to improve it then, you can take inspiration from Twitter android app.
