### ISSUE TITLE
[Bug] design of the text and images aren't good 

### ISSUE THREAD

**Issue by chetankhandait** [AKD-01/blogweet#200]
![image](https://github.com/AKD-01/blogweet/assets/121539090/0fbe67ba-baf7-4f99-b262-b63c60a003f7)
please assign me this work under GSSOC23

**Comment by AKD-01** [comment]
Please read readme.md and mention the issue no while raising the pr.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
