### ISSUE TITLE
Suggestion to add tags to each post

### ISSUE THREAD

**Issue by gSayak** [AKD-01/blogweet#202]
A new feature to add tags to each post while writing a new blog post, so that people can find their topic of interest and filter out the rest. 
The tags will be visible in the posts section and clicking on it would fetch only the tags the user wants to see, just how google photos uses the tags to filter out images.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.

**Comment by gSayak** [comment]
exams are going on currently couldn't finish it. Can work on it from after 12th June
