### ISSUE TITLE
User must have a minimum number or words before they can submit a post

### ISSUE THREAD

**Issue by gSayak** [AKD-01/blogweet#204]
Right now users can submit even one word and post in the blog section,  I want to change that so that users need to write at least 20 words before they can submit the post. 

Pls assign me the issue so I can work on it.

**Comment by gSayak** [comment]
fixed issue, and submitted <a href="https://github.com/AKD-01/blogweet/pull/205">PR#205</a> to address this. 

Pls check and close this issue.

**Comment by AKD-01** [comment]
I will check all the prs on saturday and will let you know then. You may wait or work on other issues. Thank you!
