### ISSUE TITLE
When click on share Toast shows two times in different places 

### ISSUE THREAD

**Issue by tajmalnas** [AKD-01/blogweet#212]
toast showing up on two different places and this is not good
![Screenshot (46)](https://github.com/AKD-01/blogweet/assets/111240245/7ca7a38c-298a-4202-9e24-c9ee8c8ba75b)

**Comment by AKD-01** [comment]
I have already assigned this issue to someone.

**Comment by tajmalnas** [comment]
But i have solved it efficiently and made PR

**Comment by AKD-01** [comment]
That's why one should wait for getting the issue assigned. Nevertheless please wait for me to assign the issue before working on it from next time. I will be reviewing all the prs on saturday's evening.

**Comment by tajmalnas** [comment]
Ok sorry but that toast issue is stopping me to solve my issue thats why I had done it 
Sorry if I cause you any trouble
