### ISSUE TITLE
To add a 'Sign Up' or 'Register Yourself' button

### ISSUE THREAD

**Issue by splusb** [AKD-01/blogweet#217]
I want to add a sign up button with css and js. Please assign me this issue under GSSOC'23

**Comment by Siddhant422** [comment]
Hey can you assign this issue to me under the GSSoc'23.

**Comment by vbhosale11** [comment]
Please  assign me this issue.

**Comment by splusb** [comment]
@AKD-01 , Hi can you please review this issue?

**Comment by AKD-01** [comment]
I don't want this feature currently.
