### ISSUE TITLE
About page UI improvement

### ISSUE THREAD

**Issue by KomalS2002** [AKD-01/blogweet#218]
About page UI looks bit plane, it can be enhanced and the github icon and name in the bottom are also not alligned properly.
So @AKD-01 I would like to contribute to this issue as GSSoC'23 contributor.

**Comment by vbhosale11** [comment]
Please assign me this issue under GSSOC'23.

**Comment by NishantSatere** [comment]
Can u assign this task to make I can make the about page UI look decent

**Comment by AKD-01** [comment]
Already assigned issue, please check the issue section before raising any new issue. Thank you!
