### ISSUE TITLE
[Fix]: Main content overlaps the sidebar.

### ISSUE THREAD

**Issue by subrat611** [AKD-01/blogweet#22]
Can I work on this issue?
![image](https://github.com/AKD-01/blogweet/assets/77252075/76f974e4-22da-440a-89c4-46e25a40d2ff)

**Comment by AKD-01** [comment]
Hi, @subrat611 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by AKD-01** [comment]
@subrat611 any updates or can I close this issue?

**Comment by subrat611** [comment]
Issue have been fixed you may close this issue.
