### ISSUE TITLE
Feat: Implement "Page Not Found" page for Incorrect URLs

### ISSUE THREAD

**Issue by Saurav-Pant** [AKD-01/blogweet#229]
when a user enters an incorrect URL, the website does not display a "Page Not Found" error page. As a GSSOC'23 contributor, I propose to create and implement the necessary error handling mechanism to ensure users are presented with a clear and informative "Page Not Found" page when encountering invalid URLs.
 
Assigned To: @Saurav-Pant
Labels: GSSOC'23

https://github.com/AKD-01/blogweet/assets/103263909/ed7ad7c5-475d-4f47-b99d-c8f037d1f34c

**Comment by phukon** [comment]
The issue needs urgent attention. I'll handle it promptly using **React Router v6**. Priority is to work on other project aspects too. Please assign asap. Thanks.

**Comment by AKD-01** [comment]
@phukon @Saurav-Pant 
We have this feature. Check now.
![image](https://github.com/AKD-01/blogweet/assets/83454075/401f321b-d730-4ba4-a2cf-fd58dba703e2)
