### ISSUE TITLE
Adding the option for the user to edit and delete their blogs

### ISSUE THREAD

**Issue by Akanksha-202** [AKD-01/blogweet#23]
**Describe the project you want to add with tech stack**
I want to make the website more user friendly and open the options to edit and delete past blogs by the user. I would do that with the help of HTML CSS and Js along with the help of data stored in the firebase.

Please assign this issue to me under GSSOC'23 label.

**Comment by AKD-01** [comment]
Hi @Akanksha-202 , this application is made with ReactJs. Can you make your proposed changes in ReactJS?

**Comment by Akanksha-202** [comment]
> Hi @Akanksha-202 , this application is made with ReactJs. Can you make your proposed changes in ReactJS?

Sure I can do it in ReactJS as well

**Comment by AKD-01** [comment]
Hi, @Akanksha-202, you can work on this and please refer to the Contribution guidelines on the readme once.

And also if I am the author of the blog, and want to delete it, I can.
This feature of deleting is there.
![image](https://github.com/AKD-01/blogweet/assets/83454075/4b3690cf-ee17-4e25-9fa3-f0d70b05351b)

You may work on editing feature.
All the best!

**Comment by Akanksha-202** [comment]
I made the PR for the same 
Kindly check :)
