### ISSUE TITLE
Fixing Empty Blogs

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [AKD-01/blogweet#237]
## Issue

I will be making title and text mandatory, So that the user is not able to create empty blogs.
And I will also be giving a default Image incase no url is entered while creating a blog post

## Screenshots

![image](https://github.com/AKD-01/blogweet/assets/85278243/7f44d654-795b-453f-a4bb-ac8620f9515d)

Please Assign me this issue under GSSOC'23

**Comment by heyhimansh** [comment]
hey @AKD-01 I want to work on this issue.

**Comment by AKD-01** [comment]
@Swapnil-Singh-99 You may work on this.

**Comment by Swapnil-Singh-99** [comment]
The issue is already fixed by someone
