### ISSUE TITLE
[GSSoC-2023] Changing the blog cards to make the homepage look more attractive

### ISSUE THREAD

**Issue by parag477** [AKD-01/blogweet#239]
##Button with hover effect

###What Actually I wanted to do -

Make the UI of the website more beautiful by changing the card style.

##Details:
I would like to make changes to the cards that contain blog contents to make the homepage look more attractive.

Please assign me this issue under GSSoC-2023

**Comment by AKD-01** [comment]
Already assigned issue, please check the issue section before raising any new issue. Thank you!
