### ISSUE TITLE
Adding the contact us button

### ISSUE THREAD

**Issue by Krishi1211** [AKD-01/blogweet#24]
Adding a contact us button which displays a new button for our contact us details. Also the twitter bird has no link in it.

**Comment by Kwamecody** [comment]
It will also be beneficial if the Twitter logo has a cursor on hover.

I will be very much grateful if this issue can be assigned to me.

I am GSSoC's  2023 contributor.

**Comment by AKD-01** [comment]
@Krishi1211 , Please be more elaborative and precise.

**Comment by AKD-01** [comment]
> It will also be beneficial if the Twitter logo has a cursor on hover.
> 
> I will be very much grateful if this issue can be assigned to me.
> 
> I am GSSoC's 2023 contributor.

@Kwamecody Could you please raise another issue for the same.

**Comment by Krishi1211** [comment]
> @Krishi1211 , Please be more elaborative and precise.

A footer where there will be socials of the website owners. The twitter icon is not responsive so can make it more responsive. We can also add a doubts section. If the user has any doubts then he can fill a text box with his name and submit it

**Comment by Kwamecody** [comment]
> > It will also be beneficial if the Twitter logo has a cursor on hover.
> > I will be very much grateful if this issue can be assigned to me.
> > I am GSSoC's 2023 contributor.
> 
> @Kwamecody Could you please raise another issue for the same.

Certainly

**Comment by AKD-01** [comment]
> > @Krishi1211 , Please be more elaborative and precise.
> 
> A footer where there will be socials of the website owners. The twitter icon is not responsive so can make it more responsive. We can also add a doubts section. If the user has any doubts then he can fill a text box with his name and submit it

Hi, @Krishi1211, you can work on this and please refer to the Contribution guidelines on the readme once.
About the twitter logo we haven't made a logo for the blogweet yet, so we are using that twitter logo as blogweet's logo (for now), so if you want to design something similar or better, you may.
All the best!

**Comment by Krishi1211** [comment]
> > > @Krishi1211 , Please be more elaborative and precise.
> > 
> > 
> > A footer where there will be socials of the website owners. The twitter icon is not responsive so can make it more responsive. We can also add a doubts section. If the user has any doubts then he can fill a text box with his name and submit it
> 
> Hi, @Krishi1211, you can work on this and please refer to the Contribution guidelines on the readme once. About the twitter logo we haven't made a logo for the blogweet yet, so we are using that twitter logo as blogweet's logo (for now), so if you want to design something similar or better, you may. All the best!

I am a GSSOC'2023  contributor

**Comment by AKD-01** [comment]
Okay, Also I know. You can start working on the issue. I will add the labels soon.

**Comment by AKD-01** [comment]
A contact us page has been added to the blogweet so closing the issue.
