### ISSUE TITLE
Create new posts

### ISSUE THREAD

**Issue by AKD-01** [AKD-01/blogweet#249]
Create new posts on the website with appropriate content and with all the paramters.

**Comment by AKD-01** [comment]
heyhimansh  please comment here so that i can assign it to you.

**Comment by Anurag41682** [comment]
I want to add post, How Can I?

**Comment by Anurag41682** [comment]
Can I add post to blog?

**Comment by AKD-01** [comment]
Yes, sure you can. But please add relevant text, with relevant pics. Thank you

**Comment by heyhimansh** [comment]
hey I like to work on it . only those who follow all the parameters are allowed to post a blog.

**Comment by Anurag41682** [comment]
> Yes, sure you can. But please add relevant text, with relevant pics. Thank you

I have created one please verify it.
