### ISSUE TITLE
adding link in the readme.md file

### ISSUE THREAD

**Issue by sandeep0009** [AKD-01/blogweet#25]
im raising this issue in which i want edit the readme.md file in this there should be  a link of website so that everyone can preview it easily and can see the webiste more easily

**Comment by AKD-01** [comment]
Hi, @sandeep0009  , you can work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by sandeep0009** [comment]
okay but can you tell me should i use github desktop for providing the link in the readme file or you have already some sort link for you webpage.if it so please provide me i will start working on it

**Comment by AKD-01** [comment]
You may use Github Desktop.

**Comment by sandeep0009** [comment]
okay i will finish it by today

**Comment by sandeep0009** [comment]
can u add gssoc label on it also level

**Comment by AKD-01** [comment]
Closing the issue as you haven't raised the pr. Also, anyone who forks the repo can see the link.
![image](https://github.com/AKD-01/blogweet/assets/83454075/7a971a44-0b85-4c3b-bd17-7bec25b7d5da)
