### ISSUE TITLE
💡 [REQUEST] - Side Navbar Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [AKD-01/blogweet#252]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Modification in the Side Navbar Design |
| **Solution Proposed**      |Design changes in styling, color selection, position, etc. changes|
| **Alternative Solutions**  |N/A|
| **Additional Context**     |N/A|
| **Screenshots**            | **Current Design:** ![blogweet ss 1](https://github.com/AKD-01/blogweet/assets/115794049/dd2bf712-35e7-44bc-a321-e3ca0ec336d3) **Updated Design:** ![blogweet ss](https://github.com/AKD-01/blogweet/assets/115794049/7217eb8e-6cfb-4470-a352-22300afe030a)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by op-amateur** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by AKD-01** [comment]
there is so much to work on. Please find some good issues to work on. I think sidebar is good for now.
