### ISSUE TITLE
💡 [REQUEST] - Create a post page UI improvement

### ISSUE THREAD

**Issue by Rishav1707** [AKD-01/blogweet#253]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Need some improvement in the `Create a post page` UI|
| **Solution Proposed**      |I want to add some CSS properties to enhance the `create a post page` UI that is more user-friendly and attractive|
| **Alternative Solutions**  |NA|
| **Additional Context**     |NA|
| **Screenshots**            |Example image 1 -  ![image](https://github.com/AKD-01/blogweet/assets/97666287/2c82c252-fa41-4e77-9e2a-11c5eda9049a) Example image 2 -  ![image](https://github.com/AKD-01/blogweet/assets/97666287/0c51760f-41ce-415f-8ae7-22b6ac104d3b)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
I don't need any such changes as of now.
