### ISSUE TITLE
💡 [IMPROVEMENT] - UI of scroll to top button

### ISSUE THREAD

**Issue by rayyan016** [AKD-01/blogweet#255]
Hey. The visual structure of the scroll to top button looks distorted. 

![blogissue1](https://github.com/AKD-01/blogweet/assets/102043379/3f7d5e70-6ce2-49c2-aee3-6d0c5ff7b2e6)

I would like to fix this. Could you assign this to me under GsSOC'23?

**Comment by Sandeep0306** [comment]
Hey , I would like to fix this issue .please assign me this issue under GSSOC'23.

**Comment by AKD-01** [comment]
@rayyan016 you may work on this issue. All the best!
