### ISSUE TITLE
💡 [IMPROVEMENT] - Changing the icon for the Navbar 'Contact Us'

### ISSUE THREAD

**Issue by Ayan-M-Dev** [AKD-01/blogweet#259]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | Changing icon for the Navbar 'Contact Us' |
| **Solution Proposed**      | Will change the icon for it (please refer the screenshot after I am don with the change|
| **Alternative Solutions**  | N/A |
| **Additional Context**     | N/A |
| **Screenshots**            | ![Screenshot 2023-05-27 164451](https://github.com/AKD-01/blogweet/assets/101629997/b9838c1d-eb5c-455e-9003-9f38c6fc693b) _Before_ ![My project-1 (2)](https://github.com/AKD-01/blogweet/assets/101629997/84aed4ea-5bc9-4af4-bce8-08d1ce6b8667) _After_

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
@Ayan-M-Dev please mention issue no while raising the pr. All the best.

**Comment by Ayan-M-Dev** [comment]
@AKD-01 Okay, Thanks

**Comment by Ayan-M-Dev** [comment]
@AKD-01 Please review the PR
