### ISSUE TITLE
Add a 404 not found page [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [AKD-01/blogweet#26]
Add a 404 not found page
Can you assign this to me, I want to work on this under GSSoC'23

**Comment by SONA-1111** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

**Comment by AKD-01** [comment]
Hi, @Sukhendu2002  , you can work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

@SONA-1111 I have assigned this issue to someone. So, please raise another issue.

**Comment by Sukhendu2002** [comment]
Thank you, @AKD-01, for assigning this issue to me. I will begin working on it promptly.

**Comment by PatilHarshh** [comment]
hey @AKD-01 still now error page is not added please assign me i will complete till tommorow only

**Comment by Sukhendu2002** [comment]
I solve all the conflicts, just waiting for the review and merge
