### ISSUE TITLE
💡 [IMPROVEMENT] - Setting limit to number of characters for the Title

### ISSUE THREAD

**Issue by Siva2910** [AKD-01/blogweet#261]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                              | Description                                                                                                                  |
| ---------------------------- |-----------------------------------------------------------------------------------------   |
| **Concise Description**   | Setting a limit to the number of characters for the Title                                             |
| **Solution Proposed**     | Will set a maximum length of characters that can be accepted and will be displaying in the UI that how many characters are left and will not accept any character once the maximum length has been reached |
| **Alternative Solutions** | N/A                                                                                                                           | 
| **Additional Context**    | N/A                                                                                                                           |
| **Screenshots**            | 
| ![](https://github.com/AKD-01/blogweet/assets/67836160/efd45299-e04a-4213-a1f4-ff2d33a2206a) | Screenshot displaying Maximum number of characters allowed for title |
| ![image](https://github.com/AKD-01/blogweet/assets/67836160/ea0791c3-cbe7-4e04-8879-bc9266f483f0) | Displaying how many more characters are left when entering input in title |
![](https://github.com/AKD-01/blogweet/assets/67836160/da34d9a6-1cb4-413c-8e24-b7eb24d15f0d) | Screenshot displaying When Maximum number of characters are reached |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Please wait for me to assign you the issue before working on it.

**Comment by AKD-01** [comment]
Hey, if want to set imit for the title, set for the maximum length and not the minimum length right as it doesn't make any sense for setting title length of minimum 20 characters. Also would you please make the width of textbox of the Post same as the title.
![image](https://github.com/AKD-01/blogweet/assets/83454075/1e0b353b-b9e2-46b2-be6d-d2ff95a7882f)

**Comment by Siva2910** [comment]
Do you want me to change the limit from 20 characters to some higher number right ?

**Comment by AKD-01** [comment]
No, see it's a title right. Title can be of one word, 2 words, 5 words so we should set the maximum length for the title. That the title shouldn't exceed 10 words.

**Comment by Siva2910** [comment]
yeah , since we cant count how many words they have entered i have set maximum length to 20 characters. 

I did not understand what you are trying to say  , can you connect through discord , i sent you message in discord..

**Comment by Siva2910** [comment]
i have changed the width of textbox of the post same as the title but i did not understand what you are trying to say for title related to length ..

anyother changes you want me to do ?

**Comment by AKD-01** [comment]
Please raise the pr with what all changes you made.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
