### ISSUE TITLE
🐛 [BUG] - The Images and the titles of the first two blogs are not showing 

### ISSUE THREAD

**Issue by vishnubansal001** [AKD-01/blogweet#264]
## 🐛 Bug Report Form
I want to raise the issue that at the home page of the blogtweet the first two blogs the images and the headlines of them are not showing you can check in the below screenshot which i have attached.

![Screenshot (103)](https://github.com/AKD-01/blogweet/assets/101445306/047bb621-c040-4e68-9e6a-5bbd5ba7c456)

- [yes ] I am a GSSOC'23 contributor.
- [yes ] I want to fix that issue please assign it to me

**Comment by omlondhe** [comment]
Can you assign me this issue?
I am a GSSoC23 contributor.

**Comment by AKD-01** [comment]
@vishnubansal001 you may work on this. All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
