### ISSUE TITLE
🐛 [BUG] - Two toastify message on click to share button 

### ISSUE THREAD

**Issue by tajmalnas** [AKD-01/blogweet#267]
There are two toastify message is showing up when share button is clicked and it make it look bad at interface

**Comment by AKD-01** [comment]
How can i reproduce the bug? As i can't see two toastify message.
![image](https://github.com/AKD-01/blogweet/assets/83454075/3aa20178-d435-4709-8995-ba0aec7fecfd)

**Comment by tajmalnas** [comment]
ok thank you
