### ISSUE TITLE
💡 [IMPROVE] - IMPROVE PAGE PERFORMANCE BY OPTIMIZING IMAGE ASSETS

### ISSUE THREAD

**Issue by 0xabdulkhalid** [AKD-01/blogweet#269]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | The site uses `jpg`, `png` & `svg` types of images, but the `jpg` images are always tend to be more larger in size so that the page takes more bandwith to load it |
| **Solution Proposed**      | My plan is to convert all those `jpg` images to `webp` to minimize the page load time and bandwith|
| **Additional Context**     | Unoptimized images severly affects page load time, because it may uncomfortable for the people who having a moderate internet connection|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
@0xabdulkhalid you may work on this issue. Please mention the issue no while raising the pr. All the best!

**Comment by 0xabdulkhalid** [comment]
Hello @AKD-01, PR has opened!

Kindly check it out for further details
