### ISSUE TITLE
💡 [REQUEST] - <OPEN TO ALL ISSUE - BY PROJECT ADMIN - BLOGWEET>

### ISSUE THREAD

**Issue by AKD-01** [AKD-01/blogweet#270]
| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |I want this post as the top most blog on the website. |
| **Screenshots**            |![image](https://github.com/AKD-01/blogweet/assets/83454075/58bd5264-380e-401a-8bce-eecbcab03e16)|

Anyone who wants to work on this issue, please comment below.

**Comment by prsmahajan** [comment]
what feature do you need? Can you please explain it in brief??

**Comment by AKD-01** [comment]
Visit the blogWeet website, there is this post " IMPORTANT INSTRUCTION FOR GOSSOC CONTRIBUTOR"  I want that post to remain on the top always so that whosoever open the website can see that.

**Comment by Rishav1707** [comment]
I want to work on this issue. Please assign this issue to me @AKD-01 

I have already come up with the solution - 


https://github.com/AKD-01/blogweet/assets/97666287/d10212cf-d30a-4d82-9ac3-2b22b0eba65f

**Comment by prsmahajan** [comment]
> Visit the blogWeet website, there is this post " IMPORTANT INSTRUCTION FOR GOSSOC CONTRIBUTOR" I want that post to remain on the top always so that whosoever open the website can see that.

Already done...

**Comment by AKD-01** [comment]
Hey, @Rishav1707 you may work on this. All the best!
