### ISSUE TITLE
💡 [REQUEST] - Add Dark Mode, improve the overall ui & optimize it

### ISSUE THREAD

**Issue by Vraj1103** [AKD-01/blogweet#274]
I am from GSSoC'23.
 I would like to be assigned this task.
---
 I would like to add dark mode in the site, also would like to improve the overall ui by using tailwind css, and make the contact us page responsive. Also If permitted, I would like to redesign the entire navbar and improve the content of about us page.

**Comment by AKD-01** [comment]
You may work on the dark mode and responsiveness of contact page, other than that it's fine. Also for now use css only.

**Comment by Vraj1103** [comment]
@AKD-01 can u pls assign me gssoc badge and level number

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
