### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by prsmahajan** [AKD-01/blogweet#280]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | About section breaks on a mobile device, the logo must be changed |
| **Reproduction URL** | none |
| **Reproduction Steps** | 1. Media queries<br> |
| **Screenshots** | ![blogweet vercel app_](https://github.com/AKD-01/blogweet/assets/64594624/1532d1ce-176c-40ad-adbf-22e3ff49649e) |
| **Additional Context** | Must be a certain eye-catching background, this UI looks so boring |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [✔] Chrome
- [✔] Firefox
- [✔] Safari
- [✔] Microsoft Edge
- [✔] Opera
- [✔] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [✔] Windows
- [✔] Linux
- [✔] Mac
- [✔] iOS
- [✔] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [✔] Description
- [✔] Reproduction URL
- [✔] Reproduction Steps
- [✔] Screenshots
- [✔] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [✔] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [✔] I follow Contributing Guidelines of this project.
- [✔] I have checked the current issues for duplicate problems.
- [✔] I have read the readme.

**Comment by prsmahajan** [comment]
lemme work on this. Assignee required?

**Comment by AKD-01** [comment]
@prsmahajan you may work on this. All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
