### ISSUE TITLE
Share button issue 💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by HimanshuNarware** [AKD-01/blogweet#293]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | I want to improve the hover property of the button |
| **Solution Proposed**      |Use to change the background color of the hover effect.According to the theme of the website|
| **Screenshots**            |[    
![82](https://github.com/AKD-01/blogweet/assets/83147410/25d5a433-5233-4a83-9214-23c0f1304a63)]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Issue Resolved.
