### ISSUE TITLE
💡 [REQUEST] - <ti

### ISSUE THREAD

**Issue by Kodedbykenzie** [AKD-01/blogweet#294]
Hey, I'm Precious and I am from GSSoC'23. I would like to be assigned this task.

I would like to change the layout of the home page to give it a more attractive look and also I noticed some colors contradict some, I would like to solve it.

**Comment by AKD-01** [comment]
Hey, Precious. Please elaborate on what all changes you want to make in the website along with screenshots and a brief of what you want to do. So, that it's easy for me to know if i want those changes or not. Thank you! Also, please check your issue header.
