### ISSUE TITLE
💡 - [ 1] I am from GSSoC'23. - [2 ] I would like to be assigned this task.

### ISSUE THREAD

**Issue by aditya-stoic-sharma** [AKD-01/blogweet#298]
REQUEST => making the oval button on the home page circular
- [1 ] I am from GSSoC'23.
- [ 2] I would like to be assigned this task.
---
so there is oval shaped button on the home page I can make it a perfect circular and give it a new symmetrical look 

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [1 ] I follow the Contributing Guidelines of this project.
- [2 ] I have checked the current issues for duplicate problems.
- [3 ] I have read the readme of this repository.

**Comment by aditya-stoic-sharma** [comment]
here is a screen shot of it 
![Screenshot (126)](https://github.com/AKD-01/blogweet/assets/109134266/46ede443-b56d-468f-b1a1-6a3a44f7413d)

**Comment by AKD-01** [comment]
Issue Resolved.
