### ISSUE TITLE
💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by Shr-reny** [AKD-01/blogweet#302]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

I would just like to add some more insightful blogs.

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Hey @Shr-reny, you may work on this. All the best! Please mention the issue no while raising the pr.

**Comment by AKD-01** [comment]
Closing the issue because of no response from your side for more than a week. You may raise the issue, while you're active.
