### ISSUE TITLE
💡 [REQUEST] - Blogs Heading Hover Effect Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [AKD-01/blogweet#304]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Improvement in the Hover effect of the Blogs heading |
| **Solution Proposed**      |Changing some styling of the effect, I can make it look even better |
| **Alternative Solutions**  |Style changes in the heading design |
| **Additional Context**     |N/A|
| **Screenshots**            | ![blogweet issue3 ss](https://github.com/AKD-01/blogweet/assets/115794049/080957bf-c4ff-4af1-833f-062d82ebabb8) |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Already assigned issue
