### ISSUE TITLE
Feature: Favourites and Upvoting

### ISSUE THREAD

**Issue by girish-07** [AKD-01/blogweet#31]
User shall mark the blog post which he likes as favourite.  User shall upvote and downvote blog posts, which would be shown publicly to all users (similar to Codeforces blogs)

**Comment by AKD-01** [comment]
Hi, @girish-07 , you can work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
@girish-07 Any updates??
