### ISSUE TITLE
💡 [REQUEST] - <Enhancing UI of About Section>

### ISSUE THREAD

**Issue by singhapeksha** [AKD-01/blogweet#316]
- [✅] I am from GSSoC'23.
- [✅ ] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | The About Section of the web site does not have a good UI|
| **Solution Proposed**      | I want to change the font of about section and align the paragraphs in the justified manner.|
| **Alternative Solutions**  | Enhancing the UI|
| **Screenshots**            |![image](https://github.com/AKD-01/blogweet/assets/101039104/72e09bb9-e0e8-4cc7-930c-09424bf31e60)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ ✅] I follow the Contributing Guidelines of this project.
- [✅ ] I have checked the current issues for duplicate problems.
- [✅ ] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Already raised issue, please have a look on issues section before creating a new one.
