### ISSUE TITLE
UI/UX updates and add a text editor for the create post.

### ISSUE THREAD

**Issue by AniketDutta007** [AKD-01/blogweet#32]
The user experience for the app is pretty average and in today's world UI/UX being so significant I would like to update the design of the app and provide a new look to it. As it is a blogging app with the option to create post a text editor is necessary to edit the content.
I would like to work on this issues for my GSSOC'2023.

**Comment by AKD-01** [comment]
Hi, @AniketDutta007 , you can work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by Google-Ka-Dinosaur** [comment]
Hello!! I would also like to make certain changes to the UI such as making the sidebar closable and giving it a transparent effect. Would also like to change the UI of the about page and the add a footer to the whole site.

**Comment by AKD-01** [comment]
@Google-Ka-Dinosaur please raise a new issue explaining in detail what all you want to do. Closing this issue because of no response or pr from @AniketDutta007
