### ISSUE TITLE
Improve the About page GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [AKD-01/blogweet#33]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by AKD-01** [comment]
Hi, @karthiknadar1204, you can work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by karthiknadar1204** [comment]
Sure thank you

**Comment by karthiknadar1204** [comment]
<img width="1196" alt="Screenshot 2023-05-21 at 11 50 15 AM" src="https://github.com/AKD-01/blogweet/assets/95973644/309ee61d-9786-4556-bf18-88b833ed5b07">


@AKD-01 I first ran npm i because running npm start first was giving error,
After running npm i first,i ran npm start but it is showing this error

How do i proceed.

I faced a similar issue,slightly more complex while setting the extraCloud project as well
Please help

**Comment by karthiknadar1204** [comment]
@AKD-01 any update?

**Comment by srivastavaritik** [comment]
Hey @karthiknadar1204 , the card is not aligned properly 
![image](https://github.com/AKD-01/blogweet/assets/78131705/9a79a9a7-ebfd-42e8-9c58-81d2e0e3313c)
correct this and raise another pr with some more changes. I am closing this for now.

**Comment by karthiknadar1204** [comment]
@srivastavaritik @AKD-01 Will submit pr again, please elaborate what does some more changes mean, like apart from the card alignment, should I add or delete something
