### ISSUE TITLE
💡 [REQUEST] - want to revamp the landing page of the website

### ISSUE THREAD

**Issue by Aliza30** [AKD-01/blogweet#331]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Write a concise and appropriate description of the feature request |
| **Solution Proposed**      |Describe the solution you would want|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |[Provide screenshots here]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Anubhav6205** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23. This will be my first ever open-source contribution. Please let me do it.

**Comment by Aliza30** [comment]
https://www.figma.com/file/RV86XkofFL5UgNHwuQV8CE/blogweed?type=design&node-id=0%3A1&t=VhE8oUIx3XIrgbrA-1

I WANT TO REVAME THE UI OF THE WEBSITE AND MAKE IT RESPONSIVE

**Comment by AKD-01** [comment]
@Aliza30 Nice work!👏 But i really like the structure of my present UI, its different. While keeping in mind that i don't want any structural changes, you may work on the other things. And please raise a new issue, closing this one.
