### ISSUE TITLE
💡 [REQUEST] - Enhance  : Card Ui of home page. 

### ISSUE THREAD

**Issue by Pragati-3003** [AKD-01/blogweet#335]
I would like to change the card ui of the home page by adding cool effect and background color and box shadows. 
Si, please assign this issue to me under GSSOC'23.

**Comment by Anubhav6205** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23. This will be my first-ever open-source contribution. Please let me do it.

**Comment by AKD-01** [comment]
Already raised issue. Before creating a new issue please check issue section once. Saves a lot of time. Thank you
