### ISSUE TITLE
<Feature>Contrast of colors

### ISSUE THREAD

**Issue by jayk-gupta** [AKD-01/blogweet#34]
The background color and the text color contrast could be improved [GSSoc'23]
Can I work on it?

**Comment by harshsingh32** [comment]
Hi, I would like to work on this issue under GGSoC'23.

**Comment by AKD-01** [comment]
Hi, @jayk-gupta , you can work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> Hi, I would like to work on this issue under GSSoC'23.

@harshsingh32 This issue has already been assigned to someone. Please raise another issue.

**Comment by jayk-gupta** [comment]
> Hi, @jayk-gupta , you can work on this and please refer to the Contribution guidelines on the readme once. All the best!

Yeah, thanks for assigning!

**Comment by jayk-gupta** [comment]
Please add GSSoc and level tag

**Comment by AKD-01** [comment]
Closing the issue as no updates or pr from your side.
