### ISSUE TITLE
Missing Contributing.md file

### ISSUE THREAD

**Issue by Anshika-Jain02** [AKD-01/blogweet#350]
*Missing Contributing guidelines file in the repo to provide clear guidelines to the contributors. I can add it*

Please assign me this issue under Gssoc'23 @AKD-01

**Comment by Shrejal123** [comment]
I am intersted to work on the contributing.md file. Could you please assign under gssoc23

**Comment by AKD-01** [comment]
Readme.md has all the information and guidelines related to contribution.
