### ISSUE TITLE
Responsive login page

### ISSUE THREAD

**Issue by TusharUtane07** [AKD-01/blogweet#36]
Login page is not responsive, I would like to work on responsiveness of login page.
Assign me this Issue under GSSoC 2023

**Comment by i-am-SnehaChauhan** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills.

**Comment by AKD-01** [comment]
> Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills.

@i-am-SnehaChauhan please raise another issue. This has already been assigned.

**Comment by AKD-01** [comment]
> Login page is not responsive, I would like to work on responsiveness of login page. Assign me this Issue under GSSoC 2023

@TusharUtane07, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> Login page is not responsive, I would like to work on responsiveness of login page. Assign me this Issue under GSSoC 2023

@TusharUtane07 could you please share some screenshots of where you want to do this improvement.
