### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by shruuti321** [AKD-01/blogweet#362]
I would like to improve the overall UI of the project by adding animations and css.

- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---
- [x] I follow the Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Already raised issue. Before creating a new issue please check issue section once. Saves a lot of time. Thank you
