### ISSUE TITLE
Improving the login page, about page and others.

### ISSUE THREAD

**Issue by harshsingh32** [AKD-01/blogweet#37]
I would like to work on improving the following pages of your project pages- 
About.css, About.js, Blogpost.js, CreatePost.js, Home.css, Home.js, Login.js, UserInfo.css.

**Comment by harshsingh32** [comment]
Hi, I would like to work on this issue, assign this issue to me under the GSSoC'23.

**Comment by karthiknadar1204** [comment]
@harshsingh32 Take one page at a time and resolve it instead of taking up all of them,that would block the codebase for just one person not letting others contribute,There is already and issue for the about page,main page and the login page.

**Comment by harshsingh32** [comment]
So I would like to work on createpost page.

**Comment by karthiknadar1204** [comment]
You can create an issue for the same,get assigned and then start
