### ISSUE TITLE
💡 [REQUEST] - <title>Sitemap Adiition

### ISSUE THREAD

**Issue by krishnamangal98** [AKD-01/blogweet#373]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---
SITEMAP ADDITION FOR SEO
| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Write a concise and appropriate description of the feature request |
| **Solution Proposed**      |Describe the solution you would want|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |[Provide screenshots here]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Please provide details properly before raising an issue.
