### ISSUE TITLE
Improving the createpost page.

### ISSUE THREAD

**Issue by harshsingh32** [AKD-01/blogweet#38]
Hey I would like to improve the createpost page of the project. I want to add some more features and improve the functionality of the page.

**Comment by harshsingh32** [comment]
I would like to work on this issue under GSSoC'23.

**Comment by AKD-01** [comment]
Hi, @harshsingh32 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
