### ISSUE TITLE
Redesigning the contact us page

### ISSUE THREAD

**Issue by Illaf** [AKD-01/blogweet#380]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Already raised issue. Before creating a new issue please check issue section once. Saves a lot of time. Thank you
