### ISSUE TITLE
💡 [REQUEST] - Decrease font weight of text in 'About' page to enhance user experience

### ISSUE THREAD

**Issue by riddhigupta1110** [AKD-01/blogweet#381]
- [X] I am from GSSoC'23.
- [X] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |The text of 'About' page is Poppins sans serif with font weight 700. Due to its heavy and bold nature, it impedes readability and strains the eyes of users. This results in a decreased legibility and overall poor user experience.|
| **Solution Proposed**      |Decrease the font weight to enhance the experience of user  on web pages.|
| **Screenshots**            |![Screenshot 2023-06-10 at 13-40-03 BlogWeet](https://github.com/AKD-01/blogweet/assets/112184998/ae5b4d74-a04e-4305-bceb-b5d5be32fb11)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [X] I follow the Contributing Guidelines of this project.
- [X] I have checked the current issues for duplicate problems.
- [X] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Already raised similar issues by others. Before creating a new issue please check issue section once. Saves a lot of time. Thank you
