### ISSUE TITLE
Form Validation - User is able to sumbit the form with empty feilds

### ISSUE THREAD

**Issue by Mudassirkhan2** [AKD-01/blogweet#39]
Form Validation - User is able to sumbit the form with empty feilds. -ScreenShot Attached 
![Screenshot 2023-05-20 093957](https://github.com/AKD-01/blogweet/assets/106579572/6a3e7fb0-6ed4-48b8-b3d5-8df5192e8263)
I would like to work on this issue under GSSoc 2023.

**Comment by pgs17** [comment]
As the user can submit the form with empty fields I would like to work on this form validation issue UNDER GSSOC'23

**Comment by AKD-01** [comment]
Hi, @Mudassirkhan2 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by AKD-01** [comment]
> As the user can submit the form with empty fields I would like to work on this form validation issue UNDER GSSOC'23

@pgs17 this issue is already been assigned. you may raise another issue.

**Comment by Mudassirkhan2** [comment]
@AKD-01    i have raised a PR for it can you check merge it

**Comment by AKD-01** [comment]
Resolved issue.
