### ISSUE TITLE
🐛 [BUG] -Typo Error 

### ISSUE THREAD

**Issue by bhaskarkumar1** [AKD-01/blogweet#399]
**there is a typo error in Error 404 page
Instead of oops it written opps

I know its a small error but every conribution counts. So assign me this task** 

![sc11_07](https://github.com/AKD-01/blogweet/assets/84345649/193dcd3a-1b91-4b3b-a7b9-0e817f8e73db)

**Comment by AKD-01** [comment]
Well, according to the guidelines given a typo can't be considered as a contribution. Sorry.
Thanks for making me aware about it, really appreciate it.
