### ISSUE TITLE
Improve UI of login page

### ISSUE THREAD

**Issue by KeyurGK** [AKD-01/blogweet#40]
I would like to improve the UI of login so that it enhances the current smoothness of user logging in. Looking forward to contributing under GSSoC 23
<img width="714" alt="image" src="https://github.com/AKD-01/blogweet/assets/56074740/99192bc8-4c71-4403-a954-5c0a24dceb12">

**Comment by pxiy-a** [comment]
I can improve the UI of login page. It totally goes with my techstack. 
Could assign me this issue?

**Comment by AKD-01** [comment]
Hi, @KeyurGK , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by AKD-01** [comment]
> I can improve the UI of login page. It totally goes with my techstack. Could assign me this issue?

@pxiy-a this issue has been already assigned to someone, please raise another issue.

**Comment by KeyurGK** [comment]
@AKD-01 Thanks for assigning !

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
