### ISSUE TITLE
🐛 [BUG] - Typing Error in Read Me file

### ISSUE THREAD

**Issue by Vaibhav9027** [AKD-01/blogweet#404]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | 
There is a typing error in read me file
At the instruction for Api key instead of "Root Folder" it is written "Roor Folder" |
| **Screenshots** | ![image](https://github.com/AKD-01/blogweet/assets/115151167/3281169f-143d-40be-9788-8221be2d5c22) 
I know it is a very small issue but every contribution matters so kindly assign me this issue.

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [ ] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [ ] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [ ] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [ ] I follow Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [ ] I have read the readme.

**Comment by sonustar** [comment]
please assign me this issue

**Comment by AKD-01** [comment]
Well, according to the guidelines given a typo can't be considered as a contribution. Sorry.
Thanks for making me aware about it, really appreciate it. Resolved your issue.
