### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by Vaibhav9027** [AKD-01/blogweet#405]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | Please provide a clear and concise description of the bug |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
| **Reproduction Steps** | 1. Step 1...<br>2. Step 2...<br>3. Step 3...<br>4. Step 4... |
| **Screenshots** |![image](https://github.com/AKD-01/blogweet/assets/115151167/bcf1116b-c42c-4acd-b6fc-736d6960d5e6)
| **Logs** | Relevant log output goes here |
| **Additional Context** | Please provide any other relevant information about the problem |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [ ] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [ ] Medium
- [x] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [ ] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by AKD-01** [comment]
Well, according to the guidelines given a typo can't be considered as a contribution. Sorry.
Thanks for making me aware about it, really appreciate it.
