### ISSUE TITLE
Responsive layout design

### ISSUE THREAD

**Issue by SONA-1111** [AKD-01/blogweet#41]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills. I would be happy to take it up and work on this project.

![proj](https://github.com/AKD-01/blogweet/assets/114572821/66f31f14-507e-45cf-a56a-50adca60bca0)

**Comment by AKD-01** [comment]
@SONA-1111 The same issue has already been assigned to someone else. Please raise another issue.
