### ISSUE TITLE
💡 [REQUEST] - Create a page for writing own blogs.

### ISSUE THREAD

**Issue by dwivedishrey** [AKD-01/blogweet#419]
Create a section where users can write their own blogs and it can be published on our website
Please assign this.
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
![image](https://github.com/AKD-01/blogweet/assets/83454075/51e65c45-5d79-4576-81bb-51be16b1bb5c)
Create post section is already here.
