### ISSUE TITLE
Improve the responsiveness of the main page.

### ISSUE THREAD

**Issue by surbhi400** [AKD-01/blogweet#42]
We can see that the main page is not responsive for medium and small devices. Please assign it to me under GSSoC'23. 
![Screenshot 2023-05-20 100109](https://github.com/AKD-01/blogweet/assets/77582783/4edad56a-e784-4d2c-853e-31e8d7680bcc)

**Comment by Roshnijeewani3457** [comment]
Please Assign me this issue!!

**Comment by AKD-01** [comment]
Hi, @surbhi400, you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by AKD-01** [comment]
> Please Assign me this issue!!

@Roshnijeewani3457 This issue has already been assigned to someone. Please raise another issue.

**Comment by surbhi400** [comment]
> Hi, @surbhi400, you can work on this and please refer to the Contribution guidelines on the readme once. All the best!

Ok thank you

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
