### ISSUE TITLE
💡 Minnor Update - Sidebar {GSSOC'23}

### ISSUE THREAD

**Issue by Adityavijayvargiya01** [AKD-01/blogweet#429]
- [x] I am from GSSoC'23.
- [ ] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |When in desktop mode , the sidebar width is too large and looks odd  |
| **Solution Proposed**      | I suggest that we should decrease the width of the sidebar and adjust the height and size of text accordingly |
| **Alternative Solutions**  |Alternate suggestion is  to  make sidebar as toggle as in mobile viewpoint |
| **Additional Context**     |None|
| **Screenshots**            |-|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Please check the current issues for duplicate problems before raising a new issue.
