### ISSUE TITLE
Changing the share icon to Clipboard icon

### ISSUE THREAD

**Issue by Roshnijeewani3457** [AKD-01/blogweet#43]
I would like to work on this issue under GSSoC'23.Its seems interesting and aligned with my skills. I would be happy to take it up ad work on this project. I have attached screenshoot of icon which i have to change.

![image](https://github.com/AKD-01/blogweet/assets/89697445/14c23449-ad23-4cba-a06d-b0e8b2fed595)

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by AKD-01** [comment]
@Roshnijeewani3457 @SamridhiNancy This same issue has already been assigned to someone. You may raise another issue.
