### ISSUE TITLE
 Adding User Profile Page

### ISSUE THREAD

**Issue by saicharan1901** [AKD-01/blogweet#45]
Currently, BlogWeet lacks a dedicated user profile page where users can provide essential information about themselves. I would like to add a user profile page as GSSOC'23 Contributer. 

Can you please assign this issue to me?

**Comment by AKD-01** [comment]
Hi, @saicharan1901, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response from your side.
