### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by rayyan016** [AKD-01/blogweet#48]
I would like to add a scroll to top button to the home page of BlogWeet as a GSSOC'23 contributor. Could you please assign this issue to me?

**Comment by SubhamB2003** [comment]
Hey, can you assign this task to me under GSSOC'23, I loved working on that.

**Comment by AKD-01** [comment]
Hi @rayyan016, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> Hey, can you assign this task to me under GSSOC'23, I loved working on that.

@SubhamB2003 This issue has already been assigned to someone, please raise another issue.
