### ISSUE TITLE
💡 [REQUEST] - Better Ui of About Page

### ISSUE THREAD

**Issue by Tisha6661** [AKD-01/blogweet#490]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |To enhance the Ui of the About page, which is very simple at the moment |
| **Solution Proposed**      |To cover the content in a presentable manner, and make the better Ui of the page|
| **Alternative Solutions**  |To change the content in bullet points, to make the content noticable and readable|
| **Screenshots**            |![image](https://github.com/AKD-01/blogweet/assets/98682478/f1ee3e43-bb3c-4bf7-b273-c75a9d4af549)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by AKD-01** [comment]
Already assigned issue
