### ISSUE TITLE
💡 [REQUEST] - <UI of about page>

### ISSUE THREAD

**Issue by ePSA-eJya** [AKD-01/blogweet#493]
- [x] I am from GSSoC'23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |about page |
| **Solution Proposed**      |enhancement|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |[![image](https://github.com/AKD-01/blogweet/assets/120899038/3a2972c4-b15d-4997-8673-980f8c6066a1)]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

please assignt his issue to me @AKD-01

**Comment by AKD-01** [comment]
Already assigned issue.
