### ISSUE TITLE
Avoid Blank Posts and Add Default Photo

### ISSUE THREAD

**Issue by rt-001** [AKD-01/blogweet#50]
##Issue
Currently, our platform allows blank posts to appear, which can lead to a poor user experience. Additionally, when a user creates a post without attaching a photo, no default photo is displayed. To improve the overall user experience and maintain consistency in our platform, we need to address these two issues.

1. Avoid Blank Posts
We should implement a validation mechanism that prevents users from submitting empty posts. This can be achieved by adding a check to ensure that the post content is not blank before allowing it to be published. By preventing blank posts, we can maintain the quality of the content shared on our platform and avoid instances where users inadvertently submit incomplete or meaningless posts.
2. Implement Default Photos
When a user creates a post without attaching a photo, we should automatically assign a default photo to visually represent the post. The absence of a photo can make the post appear incomplete and less engaging. By providing default photos, we can maintain a visually appealing layout throughout the platform, encouraging users to engage with posts that lack custom media attachments.

**Comment by An525ish** [comment]
I want to fix this issue please assign it to me

**Comment by AKD-01** [comment]
Hi @rt-001, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> I want to fix this issue please assign it to me

@An525ish This issue has already been assigned to someone, you may work on another issue or raise an issue.
