### ISSUE TITLE
Making the Website Responsive

### ISSUE THREAD

**Issue by rt-001** [AKD-01/blogweet#51]
I would like to make the website Responsive .
**Current Website**
<img width="1440" alt="Screenshot 2023-05-20 at 1 36 21 PM" src="https://github.com/AKD-01/blogweet/assets/76102333/403f0490-93c5-448a-8956-b0f9d4346b02">

**Comment by AKD-01** [comment]
Hi @rt-001, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
