### ISSUE TITLE
Bugs and Issues

### ISSUE THREAD

**Issue by kriti-002** [AKD-01/blogweet#52]
The things to which I could improve in this web application is:

1. Remove the twitter icon and/or replace with other meaningful icons.
2. Adding a tooltip for logout button.
3. Redirection to the newly created post just after its submitting and a flash message indicating its successful creation.
4. Footer including terms and conditions, year and copyright details could be added.
5. A highlight on the Home page/ About us/ create post when we are accessing them on the sidebar.

@AKD-01 Please give me this opportunity to fix these issues and contribute under GSSOC'23.

**Comment by AKD-01** [comment]
Hey @kriti-002, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by kriti-002** [comment]
Thank you so much for assigning me this issue. I have a question, if I want to contact you in case of any query so how could I do that?

**Comment by AKD-01** [comment]
Ofcourse on discord or github. Closing this because of no response or pr from your side. You may raise this issue again.
