### ISSUE TITLE
Website's Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [AKD-01/blogweet#53]
The website interface is nice but it can be improved by making some design adjustments. Working on the design of the website, I would like to make it even better.

**Comment by iamRabia-N** [comment]
I would like to work on this issue as a part of GSSOC-23.

**Comment by KhushiKhandelwal610** [comment]
I would like to contribute on this issue too. I have a knack for designing and I would like to make the UI more better.

**Comment by AKD-01** [comment]
Hi, @iamRabia-N, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> I would like to contribute on this issue too. I have a knack for designing and I would like to make the UI more better.

@KhushiKhandelwal610 this issue has already been assigned to someone else, please raise another issue.

**Comment by AKD-01** [comment]
Closing this because of no response from your side.

**Comment by iamRabia-N** [comment]
The PR to this issue is published 3 weeks ago.
https://github.com/AKD-01/blogweet/pull/143
