### ISSUE TITLE
Add Profile section to edit your profile.

### ISSUE THREAD

**Issue by JatinBisht2308** [AKD-01/blogweet#54]
I can add profile section to edit the user personal details.
Please add the gssoc23 lable on this issue Mam as I am a gssoc23 contribtor.
Thank you so much @AKD-01

**Comment by adityavpawar** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by AKD-01** [comment]
Hi @JatinBisht2308, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> Please assign me this issue so that I can resolve it under GSSOC-23

@adityavpawar this issue has already been assigned. Please raise another new issue.

**Comment by JatinBisht2308** [comment]
> Hi @JatinBisht2308, you may work on this and please refer to the Contribution guidelines on the readme once.
> All the best!

Thank you mam

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
