### ISSUE TITLE
Move firebase functions to a separate file

### ISSUE THREAD

**Issue by sachdevavaibhav** [AKD-01/blogweet#55]
We can move all the firebase functions to a separate file so that there is one file that controls the behavior of firebase. This way we can create interface between firebase and blogweet. If something changes in firebase in the future there will be only one file where we need to make the changes.
You can assign me the issue and I can work on it.

**Comment by prashant744** [comment]
I  can work on this issue under gssoc 23 contribution ?

**Comment by AKD-01** [comment]
Hi, @sachdevavaibhav , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by sachdevavaibhav** [comment]
@AKD-01 I am working on it and will update you accordingly.

**Comment by sachdevavaibhav** [comment]
please review the PR
