### ISSUE TITLE
Add Registration Page and Dark Theme

### ISSUE THREAD

**Issue by bkrayaguru931** [AKD-01/blogweet#57]
Registration Page:
Introduction of a dedicated registration page to allow users to create personalised accounts.
Consider including common registration fields like username, email, and password, and implement secure authentication mechanisms.
Dark Theme:
Implementation of a visually appealing dark theme option for the project's interface.

I'm hopeful that my proposal will be accepted, and I'll be given the opportunity to work on this issue under GSSoC'23.

**Comment by abcxyz31** [comment]
i can work on this task

**Comment by AKD-01** [comment]
Hi, @bkrayaguru931 , you can work on this and please refer to the Contribution guidelines on the readme once. 
Please work on the registration page for now as dark mode toggle issue has already been assigned to someone else.
All the best!

**Comment by AKD-01** [comment]
> i can work on this task

@abcxyz31 please raise another new issue, this issue has already been assigned.

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
