### ISSUE TITLE
More Sharing option

### ISSUE THREAD

**Issue by khushigupta123** [AKD-01/blogweet#59]
Current codebase only copies the link on clipboard while sharing, I would like to add option for sharing the blog on twitter, WhatsApp and other social media handles.

I am GSSOC'23 contributor, kindly assign this issue to me.

**Comment by AKD-01** [comment]
Hi, @khushigupta123 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by khushigupta123** [comment]
> Hi, @khushigupta123 , you can work on this and please refer to the Contribution guidelines on the readme once. All the best!

Sure, I will check out readme before working.
Thank you!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
