### ISSUE TITLE
Make the main page responsive

### ISSUE THREAD

**Issue by karthiknadar1204** [AKD-01/blogweet#60]
Proposed solution:
We could implement a hamburger icon and make the side menu as the top menu ,align the blogs in one line imrpovig the ui and add a scroll up button when the user has scrolled beyond a certain level.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by AKD-01** [comment]
Hi @karthiknadar1204 , i don't think that there is a need for a hamburger menu, but you can surely work on that scroll

**Comment by karthiknadar1204** [comment]
Will do but how will you align the sidebar in a smaller screen

**Comment by AKD-01** [comment]
Will see that in the future, you may work on the scroll issue for now.

**Comment by karthiknadar1204** [comment]
Will implement scroll on monday/tuesday
Had my exams going on

**Comment by AKD-01** [comment]
Closing this because of no response or pr on this issue from your side.
