### ISSUE TITLE
Ehnance User experience and make Title clickable !

### ISSUE THREAD

**Issue by SaurabhDwivedi231003** [AKD-01/blogweet#61]
Issue : 1
![Screenshot 2023-05-20 182300](https://github.com/AKD-01/blogweet/assets/128415215/d16c87e3-1611-4304-8144-5a238a3e83ef)
Title : 'BlogWeet' can be made clickable so that user can navigate to about section directly and we would not require extra about section , this enhance user experience and make app more simple and clean.

Issue : 2

![Screenshot 2023-05-20 182149](https://github.com/AKD-01/blogweet/assets/128415215/708f73fe-daa9-4c00-88ef-227b8fe12a59)
Hover effect looks over and unwanted that can be enhanced by using CSS.

Issue : 3
![image](https://github.com/AKD-01/blogweet/assets/128415215/3846c138-fdc5-4c71-83a6-246a5455697d)
Website is not responsive which must. I am good in media queries and can improve this.

If I will get a chance to work in this project I will overall enhance this project.
Thankyou :)

**Comment by AKD-01** [comment]
Hi, @SaurabhDwivedi231003 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by SaurabhDwivedi231003** [comment]
Thankyou so much !

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.

**Comment by SaurabhDwivedi231003** [comment]
Sorry for being late due to EndSem Exams , I'm putting my efforts and will reflect soon!
