### ISSUE TITLE
add footer 

### ISSUE THREAD

**Issue by An525ish** [AKD-01/blogweet#62]
A footer can be made to access all the social links and for branding and copyrights. I want to work on this issue Please assign it to me

**Comment by AKD-01** [comment]
Hi, @An525ish , Can you please elaborate more on what all things you want to add in the footer, is it really necessary for this application?

**Comment by mahekkg** [comment]
Hey @AKD-01 
 Adding a footer to the application can provide various benefits for functionality and user experience. Consider including navigation links, social media icons, copyright information, terms of service, privacy policy, and contact information. These elements enhance navigation, brand visibility, legal compliance, and user trust. Customize the footer based on your application's goals and target audience will be beneficial.
Please assign me this task under GSSoC'23
Thank you

**Comment by An525ish** [comment]
> Hi, @An525ish , Can you please elaborate more on what all things you want to add in the footer, is it really necessary for this application?

Sure, as you are having a blog website, It will be easier for those who want to collaborate or may find some corrections in your blogs. Other than this you can also give the links of your social media handles to increase your reach. and there would be copyright so that no one can copy your content

**Comment by sagarb2003** [comment]
Hey @AKD-01 
Adding a footer  improves a website's overall usability
As it is a blog website so it will require a simple footer
and also you want to add some more specifications I will make sure to add that
Please assign me this task under GSSoC'23

Thank You

**Comment by AKD-01** [comment]
Hi, @An525ish , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.

**Comment by sagarb2003** [comment]
hey @AKD-01 you didnt give me opportunity to do this task

**Comment by AKD-01** [comment]
@sagarb2003 raise a new issue, if you want to work

**Comment by sagarb2003** [comment]
@AKD-01 I have to raise the issue for same task or some another task
plzz tell....

**Comment by AKD-01** [comment]
I think folks are working on this issue, please raise a new issue.
