### ISSUE TITLE
Responsive logo and better object shadows and share buton

### ISSUE THREAD

**Issue by PoulavBhowmick03** [AKD-01/blogweet#63]
I want to add the home page to the logo so that on clicking the logo, user is directed back to the website
Also, I want to add link to the twitter logo so that on clicking it, user is directed to the twitter account
And I want to change the UI of the share button, the shadows
Please assign it to me

**Comment by PoulavBhowmick03** [comment]
Also, on the second box, nothing is being displayed, if I am told what to add there, I can do that too

**Comment by AKD-01** [comment]
> I want to add the home page to the logo so that on clicking the logo, user is directed back to the website Also, I want to add link to the twitter logo so that on clicking it, user is directed to the twitter account And I want to change the UI of the share button, the shadows Please assign it to me

Hi @PoulavBhowmick03 , you can work on `I want to add the home page to the logo so that on clicking the logo, user is directed back to the website` and `And I want to change the UI of the share button, the shadows`

**Comment by AKD-01** [comment]
> Also, on the second box, nothing is being displayed, if I am told what to add there, I can do that too

please elaborate this more

**Comment by PoulavBhowmick03** [comment]
![Screenshot 2023-05-21 012049](https://github.com/AKD-01/blogweet/assets/133862694/3e0070be-bfb2-45e9-bb23-997c3f1c45d7)
the 2nd div isn't showing anything. If required, I can add what is to be displayed there

**Comment by PoulavBhowmick03** [comment]
Can I get the twitter account I should link to? @AKD-01

**Comment by PoulavBhowmick03** [comment]
I didn't realise this was in REACT JS. I want it to be unassigned as I have no knowledge of Reactjs
I am sorry for not seeing the codebase prior to making the issue
