### ISSUE TITLE
[BUG FIXES] Fixing bugs related to form submission

### ISSUE THREAD

**Issue by Yash7426** [AKD-01/blogweet#64]
Bugs -
1. User is able to submit empty form.
2. No default photo is shown if user doesn't provide an image link.
References for above bugs -
![pop](https://github.com/AKD-01/blogweet/assets/119874901/543914c4-dc53-4369-a0a0-4be77ed238b6)
![pop2](https://github.com/AKD-01/blogweet/assets/119874901/aa5e4517-6f27-45fe-acd0-17cb7b8c301e)

I would like to work on this issue ender the GSSoc'23 program.Please assign it to me.

**Comment by AKD-01** [comment]
Hi @Yash7426 , Sorry but I have already assigned this issue to someone else. Probably you can raise some other issue.
