### ISSUE TITLE
I want to make contact us page 

### ISSUE THREAD

**Issue by bhaskarkumar1** [AKD-01/blogweet#65]
Please assign me the task to make a contact us page by providing me details of email, social media handles, etc.

**Comment by AKD-01** [comment]
Hi, @bhaskarkumar1 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by bhaskarkumar1** [comment]
thank you @AKD-01 . I will start working on it.

**Comment by bhaskarkumar1** [comment]
please check @AKD-01 ,  I have made a pull request , I have made it responsive too
https://github.com/AKD-01/blogweet/pull/152
