### ISSUE TITLE
Add Readme Badges

### ISSUE THREAD

**Issue by UjjwalSharma01** [AKD-01/blogweet#68]
hello,
i want to add readme badges, image for the reference is attached, this image is just for the reference, to make it clear of what im talking about.
![image](https://github.com/AKD-01/blogweet/assets/113621084/898f4f39-acfa-40f2-91d2-c384b2317b4b)

**Comment by AKD-01** [comment]
Hi, @UjjwalSharma01 , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by S-ishita** [comment]
@AKD-01 kindly refer #47 
this issue is already raised earlier

**Comment by AKD-01** [comment]
@S-ishita aren't they different?

**Comment by S-ishita** [comment]
No he is refering to same thing. @AKD-01

**Comment by AKD-01** [comment]
Oh okay. @UjjwalSharma01  you may work on any new issue as this issue ghas already been assigned. Thank you!

**Comment by UjjwalSharma01** [comment]
@AKD-01 alright
