### ISSUE TITLE
Data not Provided

### ISSUE THREAD

**Issue by kumarankit999** [AKD-01/blogweet#70]
If we see below, We can see anything in preview of the blog. There isn't any picture and short note.
It seems to be not looking good, We can add this pictures and info, and all users have to upload picture and short note for their blog

![image](https://github.com/AKD-01/blogweet/assets/111564362/999ffe4c-055d-44e8-9604-bc2294bc1375)

**Comment by AKD-01** [comment]
Hi @kumarankit999 , I think probably we can make these fields necessary or have a default auto-generated image in case the user does not upload any image. 
You can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by AKD-01** [comment]
resolved issue
