### ISSUE TITLE
improve the individual blogs on opening the blog

### ISSUE THREAD

**Issue by karthiknadar1204** [AKD-01/blogweet#73]
proposed solution:
When the blog is opened,the content placement doesnt look engaging 
We could create a separate container and with some rounded borders,we can add the blog image and content inside the container.
Further we can make the name of the author name and date of publish look more prominent by containing them in a small horizontal container.

We can also align the heading of the blog accordingly and same goes for the share button

**Comment by karthiknadar1204** [comment]
I can work on this issue under gssoc'23

**Comment by AKD-01** [comment]
Hey @karthiknadar1204, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by karthiknadar1204** [comment]
Starting work on this issue

**Comment by karthiknadar1204** [comment]
Will try submitting pr for review tomorrow

**Comment by karthiknadar1204** [comment]
Hii will clear this issue tomorrow @AKD-01 , Exams got over today
Thank you for your patience

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.

**Comment by karthiknadar1204** [comment]
@AKD-01 I couldn't respond because i was already working on an issue for under your project, please reopen this issue, will resolve it asap
