### ISSUE TITLE
Signup/Signin through email and password

### ISSUE THREAD

**Issue by Yash7426** [AKD-01/blogweet#74]
User can sign up to the website using their email and password , which can be used to sign-in again using the credentials.
I would like to work on the issue , please assign it to me

**Comment by Pragati-3003** [comment]
Hey @AKD-01 
I would like to work on this issue.
Please assign this issue to me under GSSOC'23.
Thanks

**Comment by AKD-01** [comment]
Hey @Yash7426, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
> Hey @AKD-01 I would like to work on this issue. Please assign this issue to me under GSSOC'23. Thanks

@Pragati-3003 this issue has already been assigned, please raise another new issue.

**Comment by Pragati-3003** [comment]
Okay!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
