### ISSUE TITLE
Twitter icon not linked

### ISSUE THREAD

**Issue by Kwamecody** [AKD-01/blogweet#75]
Hello there,

The Twitter icon on the page is not linked to any address. It will also be beneficial if the Twitter logo has a cursor on hover.

I will be very much grateful if this issue can be assigned to me.

I am GSSoC's 2023 contributor.

Thank you in advance.

**Comment by AKD-01** [comment]
@Kwamecody Someone else is already working on the same issue, please check the issue section before raising any new issue.
Meanwhile, you can check for another bugs for correction or ui enhacements that are needed and not have been raised till now.
Would love to assign that to you.

**Comment by Kwamecody** [comment]
> @Kwamecody Someone else is already working on the same issue, please check the issue section before raising any new issue. Meanwhile, you can check for another bugs for correction or ui enhacements that are needed and not have been raised till now. Would love to assign that to you.

Well noted with thanks.
