### ISSUE TITLE
SEO of the Complete App

### ISSUE THREAD

**Issue by Girishnikam** [AKD-01/blogweet#76]
[GSSoC 2023] SEO-friendly website can increase website credibility, improve user experience and get more users on our website. For making the website SEO friendly I'll like to implement following things

- Optimize the title tags and meta descriptions
- Using keywords in the website content (will perform proper research for keywords across all the search engines)
- Include keyword-rich anchor text in links
- Compressing the media (images, illustrations) to make sure website loads faster
- Clean up and organize the complete code
- (Optional) Implement various Google tools like Google Analytics, Google Search Console to see how site is performing in Google search results

Find the attachment of example, how optimization will help to boost performance of the website
![use of title and meta description optimisation](https://github.com/AKD-01/blogweet/assets/84145346/c4174237-51ed-4c72-bad2-d7ef90b3235b)

**Comment by AKD-01** [comment]
Hey @Girishnikam, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by Girishnikam** [comment]
Sure, thank you!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
