### ISSUE TITLE
[Feature] Add a "Scroll to the Top" Button

### ISSUE THREAD

**Issue by parthksingh1** [AKD-01/blogweet#77]
I would like to add a scroll up to the top Button, to enhance user Experience, please assign me this under @GSSOC'23 to make it better.

**Comment by AKD-01** [comment]
Hey @parthksingh1, Please check the issue section before raising a new issue. This issue has already been assigned to someone. You may raise any other new issue. Thank you!

**Comment by parthksingh1** [comment]
Thank you @AKD-01 for letting me know and Sorry for the inconvenience.
