### ISSUE TITLE
Add Contact Us page

### ISSUE THREAD

**Issue by sajalbatra** [AKD-01/blogweet#80]
I will help many user as is there will be a contact us page.
Please assign this issue to me under GSSOC'23.

**Comment by Pragati-3003** [comment]
Hey @AKD-01 
I would like to work on this issue.
Please assign this issue to me under GSSOC'23.
Thanks

**Comment by AKD-01** [comment]
@sajalbatra please check the issue sections once, before raising an issue. This issue has already been assigned to someone. You may raise new issue and work on that.

**Comment by AKD-01** [comment]
> Hey @AKD-01 I would like to work on this issue. Please assign this issue to me under GSSOC'23. Thanks

@Pragati-3003 This issue has already been assigned. Please raise another new issue.
