### ISSUE TITLE
Add genre list in navbar 

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [AKD-01/blogweet#83]
We can add genre list to the navbar to classify different blogs of different fields.
I would like to work on this issue . Please assign it to me under GSSOC'23

**Comment by AKD-01** [comment]
@KhushiKhandelwal610, you may work on this after completing your first issue. Please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by AKD-01** [comment]
Closing this because of no response or pr from your side.
