### ISSUE TITLE
Add feature connection to wallet via metamask

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [AKD-01/blogweet#84]
This feature will allow users to access the website, ability to save and organize favorite blog posts, like and rate blogs. The blogs act as NFTs! themselves.
I would like to work on this issue. Please assign it to me under GSSOC'23

**Comment by AKD-01** [comment]
@KhushiKhandelwal610 may work on this, but will you be able to work on three issues simultaneously? I am not assigning it to you for now, first complete the earlier issues and then ask me again in the future.

Thank you!

**Comment by KhushiKhandelwal610** [comment]
Ok
