### ISSUE TITLE
Add Back Button in Login Page 

### ISSUE THREAD

**Issue by parthksingh1** [AKD-01/blogweet#87]
I would like to add Back Button in Login Page to enhance the User Experience, by adding it if user doesn't want to login and want to go back on his previous page can go easily by addition of Back Button.

![Screenshot (12)](https://github.com/AKD-01/blogweet/assets/128512586/7c5f22fb-605e-43dc-9090-23811e814ec4)

**Comment by parthksingh1** [comment]
Please assign me this under @GSSOC'23 to make it Better

**Comment by AKD-01** [comment]
Hi, @parthksingh1, you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by tajmalnas** [comment]
can i do this i can do this in minutes

**Comment by AKD-01** [comment]
@tajmalnas you may work on this.

**Comment by tajmalnas** [comment]
Sure thank you
