### ISSUE TITLE
Add contribution graph

### ISSUE THREAD

**Issue by S-ishita** [AKD-01/blogweet#90]
I want to add contribution graph in readme. Please assign this issue to me under GSSOC

**Comment by AKD-01** [comment]
@S-ishita you may work on this and please refer to the Contribution guidelines on the readme once.
Also, I think you have been working on other issues as well. So, for the next issue, list all the bugs/ui enhancements you want to make in a single issue in points. And while raising the pr mention that issue. Thanks!
